name: Build Base Images

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Build images on different platform'
        required: true
        default: 'linux/amd64'
        type: choice
        options:
        - linux/amd64
        - linux/arm64
        - linux/amd64,linux/arm64
      cri:
        description: 'cri'
        required: true
        default: 'docker'
        type: choice
        options:
        - docker
        - containerd
      version:
        description: 'Kubernetes version'
        required: true

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Alicloud Docker registry
      uses: docker/login-action@v2
      with:
        registry: registry.cn-shanghai.aliyuncs.com
        username: ${{ secrets.ALI_REGISTRY_USER }}
        password: ${{ secrets.ALI_REGISTRY_PASS }}
    - name: Build and push images
      run: |
        sudo bash auto-build.sh --username="${{ secrets.ALI_REGISTRY_USER }}" --password="${{ secrets.ALI_REGISTRY_PASS }}" --cri="${{ env.CRI }}" --k8s-version=v"${{ env.VERSION }}" --buildName=registry.cn-shanghai.aliyuncs.com/jibutech/kubernetes:"${{ env.VERSION }}"-base --platform=amd64 --push
      env:
        PLATFORM: ${{ inputs.platform }}
        CRI: ${{ inputs.cri }}
        VERSION: ${{ inputs.version }}
